### PR TITLE
Add Python3 Support

### PR DESCRIPTION
**Pull request by joshblum**
@charlax this builds on @young-udemy 's PR #5  finishing the migration to python3. Please let me know if you have any additional review comments. Would love to see the updated package on pypi for use :)

### CODE REVIEW

**Comment by joshblum** [comment]
also, I signed the CLA agreement but I think the check will fail because @young-udemy has not, what is a good workaround for this? I'm not sure that @young-udemy is still active on github

**Comment by joshblum** [comment]
Thanks @young-udemy !!

**Comment by charlax** [comment]
Thanks a lot! This is awesome.

**Comment by joshblum** [comment]
Happy to help!!

**Pull request merged**
